Added the service class method to the modelcard
ersilia-os/ersilia pull request #1173
Opened 2024-06-25 17:48 UTC by Malikbadmus

Related to this (comment)[https://github.com/ersilia-os/ersilia/issues/1072#issuecomment-2185852513]

**Description**

Make `ersilia catalog --local --more` verbose in its output including information about how the model was fetched.

**Changes made**

- Added `get_service_class` method to the `Localcard` class in `card.py`.
- Added `service_class` method to the `Modelcard`.
- Added a series of private method to get the status, input and output type of a model in `catalog.py`.
- Modified  Local to display this new additional information.

**Status**

- Old model local catalog output 
- New model local catalog output

Related to #1072

2024-06-25 17:51 UTC, Malikbadmus commented
@DhanshreeA , this is the output now, added three (3) additional information to it.

![Result](https://github.com/ersilia-os/ersilia/assets/46167222/b345cbb7-f92d-473b-8c48-22da9523c114)

2024-06-26 06:42 UTC, DhanshreeA commented
> @DhanshreeA , this is the output now, added four (4) additional information to it.
> 
> ![Result](https://private-user-images.githubusercontent.com/46167222/342851544-b345cbb7-f92d-473b-8c48-22da9523c114.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzODQzNDYsIm5iZiI6MTcxOTM4NDA0NiwicGF0aCI6Ii80NjE2NzIyMi8zNDI4NTE1NDQtYjM0NWNiYjctZjkyZC00NzNiLThjNDgtMjJkYTk1MjNjMTE0LkpQRz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDA2NDA0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1ZjVjYzJiNTM2MWFhMjkzY2ZiMjg1OGQwOTVhYTNkNTJmOGM1N2Y0MmI4ZTA1MTk3MGZmMTI2OWM2Yjk0NDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oJO0VK5eB5OBQBCWOpnBy20VdTL6HvTu1pifd-3lFDQ)

Not endorsing screen shots but the output looks good to me! :)

2024-06-26 07:07 UTC, DhanshreeA requested changes

2024-06-26 07:07 UTC, DhanshreeA commented on ersilia/hub/content/card.py
> +    def get_service_class(self, model_id):
Let's add a docstring to this method!

2024-06-26 07:08 UTC, DhanshreeA commented
Hey @Malikbadmus great work! Thank you. Few small comments but we can absolutely merge this today.

2024-06-26 08:31 UTC, Malikbadmus commented
> Hey @Malikbadmus great work! Thank you. Few small comments but we can absolutely merge this today.

Changes applied.

2024-06-26 08:46 UTC, DhanshreeA commented
LGTM!

2024-06-26 08:46 UTC, merged