Removal of Ersilia current command
ersilia-os/ersilia pull request #1284
Opened 2024-10-03 09:20 UTC by Ajoke23

Thank you for taking your time to contribute to Ersilia, just a few checks before we proceed
- [ ] Have you followed the guidelines in our [Contribution Guide](https://github.com/ersilia-os/ersilia/blob/master/CONTRIBUTING.md)
- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you successfully ran tests with your changes locally?

**Description**

Remove the ersilia current command

**Changes to be made**
- Delete current.cmd() line of code
- Delete all line of code in current.py

**Status**

**To do**

Run it locally

Is this pull request related to any open issue? If yes, replace issueID below with the issue ID

Related to #1267

2024-10-03 09:44 UTC, Ajoke23 commented
Hi @DhanshreeA 
I have successfully removed the current command. I have attached output after testing it locally
<img width="407" alt="successfully removal of current command" src="https://github.com/user-attachments/assets/c0523d36-001d-4a10-b65b-62282342e3c8">

This is the main pull request. I have initially created a pull request yesterday for this same task. Can i go ahead of close the previous pull request #1282 or which pull request is preferable

CC @GemmaTuron

2024-10-03 11:23 UTC, Ajoke23 commented
Yes, it's. This is the pull request I want @DhanshreeA to got through.
I am waiting for feedback if I can go ahead and close pull request #1296

2024-10-03 11:24 UTC, Ajoke23 commented
> hi @Ajoke23 isn't this a duplicate PR to the one you previously opened?

Yes, it's. This is the pull request I want @DhanshreeA to got through.
I am waiting for feedback if I can go ahead and close pull request #1282

2024-10-04 15:10 UTC, adebisi4145 commented
Hello @Ajoke23, next time just rename the branch from github.

[Here's](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch) a detailed explanation on how to go about it

2024-10-05 13:35 UTC, DhanshreeA approved these changes

2024-10-06 20:09 UTC, dzumii requested changes

2024-10-06 20:21 UTC, dzumii commented
@Ajoke23 You can also run the `ersilia current` command (before and after you made changes) and post the output here

2024-10-07 06:46 UTC, Ajoke23 commented on ersilia/cli/commands/current.py
> -from . import ersilia_cli
Hi @dzumii 
The entire file was removed

2024-10-07 06:52 UTC, Ajoke23 commented
> @Ajoke23 You can also run the `ersilia current` command (before and after you made changes) and post the output here

Hi @dzumii I posted the output after changes was made above

2024-10-08 10:37 UTC, dzumii commented
@DhanshreeA I have tested and reviewed this PR and I think this is good to go

2024-10-08 15:04 UTC, DhanshreeA commented
> Hi @DhanshreeA I have successfully removed the current command. I have attached output after testing it locally <img alt="successfully removal of current command" width="407" src="https://private-user-images.githubusercontent.com/71567200/373199762-c0523d36-001d-4a10-b65b-62282342e3c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0MDAwNTMsIm5iZiI6MTcyODM5OTc1MywicGF0aCI6Ii83MTU2NzIwMC8zNzMxOTk3NjItYzA1MjNkMzYtMDAxZC00YTEwLWI2NWItNjIyODIzNDJlM2M4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDE1MDIzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjOGI3MWNiNjE0MWMzOWUyNDRiMDlkOWNkMzdjOWU3NjQ5NTYyZGZiMDZlMTRkMjA4ZTFiODEzMzdhOTI1M2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.85nFIb2R9pGzDKGcSyViri1lP2fuPs7bUR4J7hg2OeA">
> 
> This is the main pull request. I have initially created a pull request yesterday for this same task. Can i go ahead of close the previous pull request #1282 ?
> 
> CC @GemmaTuron

@Ajoke23 in the screen shot you have shared, it seems you are not running the `ersilia` command correctly itself. It is spelled as `erisilia` in your screen shot.

2024-10-08 19:32 UTC, Ajoke23 commented
Hi @DhanshreeA that was a typo error. I will try again and give you a feedback 
> > Hi @DhanshreeA I have successfully removed the current command. I have attached output after testing it locally <img alt="successfully removal of current command" width="407" src="https://private-user-images.githubusercontent.com/71567200/373199762-c0523d36-001d-4a10-b65b-62282342e3c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0MDAwNTMsIm5iZiI6MTcyODM5OTc1MywicGF0aCI6Ii83MTU2NzIwMC8zNzMxOTk3NjItYzA1MjNkMzYtMDAxZC00YTEwLWI2NWItNjIyODIzNDJlM2M4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDE1MDIzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjOGI3MWNiNjE0MWMzOWUyNDRiMDlkOWNkMzdjOWU3NjQ5NTYyZGZiMDZlMTRkMjA4ZTFiODEzMzdhOTI1M2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.85nFIb2R9pGzDKGcSyViri1lP2fuPs7bUR4J7hg2OeA">
> > 
> > This is the main pull request. I have initially created a pull request yesterday for this same task. Can i go ahead of close the previous pull request #1282 ?
> > 
> > CC @GemmaTuron
> 
> @Ajoke23 in the screen shot you have shared, it seems you are not running the `ersilia` command correctly itself. It is spelled as `erisilia` in your screen shot.

2024-10-08 21:20 UTC, P-Mefut commented
Okay great @Ajoke23, your work ready to be merged then... I've ran the test and it's in good standing...

2024-10-08 21:22 UTC, Ajoke23 commented
> Okay great @Ajoke23, your work ready to be merged then... I've ran the test and it's in good standing...

Thanks a lot. @dzumii also ran it too and I am good to go
@DhanshreeA will merge it soonest, I believe so.

2024-10-09 08:27 UTC, merged