Removed the `api` command from the Circleci workflow
ersilia-os/ersilia pull request #1305
Opened 2024-10-09 09:46 UTC by mercybassey

Thank you for taking your time to contribute to Ersilia, just a few checks before we proceed
- [x] Have you followed the guidelines in our [Contribution Guide](https://github.com/ersilia-os/ersilia/blob/master/CONTRIBUTING.md)
- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you successfully ran tests with your changes locally?

**Description**

The `api` command in Ersilia is deprecated; therefore, any workflow that uses it will fail. 

**Changes to be made**

This PR aims to remove the  `api` command from the Circle CI workflow.

**Status**

This PR removes the `api` command from the Circle CI workflow.

Is this pull request related to any open issue? If yes, replace issueID below with the issue ID

Related to #1303

2024-10-09 10:58 UTC, mercybassey commented
Hello @DhanshreeA this PR is ready for review. Thanks.

2024-10-10 06:36 UTC, DhanshreeA requested changes

2024-10-10 06:36 UTC, DhanshreeA commented on .circleci/config.yml
Hi @mercybassey we actually need to use the `run` command, instead of the `api` command.

2024-10-10 06:46 UTC, mercybassey commented on .circleci/config.yml
Okay. I'll fix it

2024-10-10 06:53 UTC, mercybassey commented
@DhanshreeA I have added the `run` command instead. Thanks.

2024-10-10 07:01 UTC, DhanshreeA approved these changes

2024-10-10 07:19 UTC, merged