Add --all flag to delete all locally available models
ersilia-os/ersilia pull request #1317
Opened 2024-10-10 11:51 UTC by JoyProg

**Description**

This feature enhances Ersilia's delete command by adding the functionality to delete multiple models.

**Changes Made**

 - Implemented a delete all models feature.
- Refactored the code to eliminate redundancy, ensuring both single and multiple model deletions now call a base method by passing in the model ID.

Related to #1265

2024-10-10 14:59 UTC, P-Mefut commented
Hi @JoyProg could you please share your logs output, I've tried running test and I'm getting a no such option for the --all tag

[output.log](https://github.com/user-attachments/files/17330136/output.log)

2024-10-10 15:24 UTC, JoyProg commented
Hi @P-Mefut. I do not get the error. I've attached the log file.  Can you verify if the file you have locally reflects the changes? 
[output.log](https://github.com/user-attachments/files/17330484/output.log)

2024-10-10 20:05 UTC, JoyProg commented
Hi @P-Mefut, are you still getting the same output?

2024-10-12 18:58 UTC, P-Mefut commented
Hi @DhanshreeA I've checked again and everything is in good standing, the code works just fine👍

2024-10-13 07:55 UTC, DhanshreeA requested changes

2024-10-13 07:55 UTC, DhanshreeA commented on ersilia/cli/commands/delete.py
> +        short_help="Delete model from local computer",
Maybe we can rephrase this better, something like, "Delete model(s) available locally"

2024-10-13 07:55 UTC, DhanshreeA commented on ersilia/cli/commands/delete.py
> +        help="Delete model from local computer. The BentoML bundle is deleted, as well as the files stored in "
"Delete model(s) available locally. The BentoML bundle is deleted, as well as the files stored in the EOS directory."

2024-10-16 08:01 UTC, dzumii commented
Hello @JoyProg have you implemented the requested changes here?

2024-11-07 11:00 UTC, DhanshreeA approved these changes

2024-11-07 11:02 UTC, merged