Performace Improvement on the run CLI(ersilia-os#1299)
ersilia-os/ersilia pull request #1353
Opened 2024-10-26 18:52 UTC by Abellegese

Thank you for taking your time to contribute to Ersilia, just a few checks before we proceed
- [ ] Have you followed the guidelines in our [Contribution Guide](https://github.com/ersilia-os/ersilia/blob/master/CONTRIBUTING.md)
- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you successfully ran tests with your changes locally?

**Description**

Overall performance of the run CLI has been increased substantially by making the changes below(comparison results will be given at #1299)

1) Asynchronous and concurrent based key converter at the compound identifier
2) Caching(with dynamic custom cache size) key conversion results for smiles both from the APIs and from rdkit **(main performance boost)**
3) Adding a valid smiles checker
4) api schema and information file reader function improvement
5) reduction in the unnecessary heavy app layers
6) more

Related to #1299

2024-10-29 07:34 UTC, DhanshreeA requested changes

2024-10-29 08:24 UTC, DhanshreeA commented on ersilia/hub/fetch/fetch.py
> +        self._standard_csv_example(model_id)
This was removed in [here](https://github.com/ersilia-os/ersilia/pull/1311/files#diff-da367f6acda96f79484d9ac4e6bf8a92230b0705f7f34827616a7b7bef6d20faR216) but it is important for Ersilia's functioning and is therefore being reintroduced again.

2024-10-29 09:03 UTC, DhanshreeA requested changes

2024-10-29 09:06 UTC, DhanshreeA commented
Hey @Abellegese this looks fantastic! Please implement the small comments around code clean up/refactoring. And if you could add a note explaining your usage of `nest_asyncio`, including as much detail as possible - what was the problem you encountered, which pipelines were failing (you can paste logs as well). This would be good documentation for coming back to it in the future.

2024-10-30 17:07 UTC, Abellegese commented
### Issue Summary
In one the stages I encountered an error  due to multiple asynchronous event loops. While running locally and using `nox`, the app worked fine. However, GitHub Actions raised a `RuntimeError` related to "multiple async event loops" due to the Jupyter notebook in the final test stage leaking its async event loop, leading to interference across stages.

### Files Impacted
These files initialize asynchronous event loops:
- `standard_api.py`
- `compound.py`
- `fetch.py` (command execution)

### GitHub Workflow Impacted Stages
The issue occurs between the first and last stages:
1. `Deploy and test ersilia on PR / build (pull_request)`
2. `test-colab-notebook` (notebook execution leaks async event loop)

### Solution: Using `nest_asyncio`
To handle nested event loops and prevent inter-stage communication issues, I integrated `nest_asyncio`, which allows us to reuse the event loop in each file without conflicts. `nest_asyncio` is compatible across Python versions and has resolved the issue in GitHub Actions.

2024-10-31 06:32 UTC, DhanshreeA approved these changes

2024-10-31 06:32 UTC, merged