Merging NEW_CONTRIBUTORS.md in CONTRIBUTION.md
ersilia-os/ersilia pull request #199
Opened 2022-04-08 17:06 UTC by sayantani11

Extends #44

2022-04-08 21:39 UTC, GemmaTuron requested changes
Hi @sayantani11 

I would like you to add your sections but do not remove so many parts from the original document thanks

2022-04-09 02:43 UTC, sayantani11 commented
> Hi @sayantani11
> 
> I would like you to add your sections but do not remove so many parts from the original document thanks

I feel the contributing guidelines had a lot of steps that were for beginners but those documents already exist.  The new-contribution.md file consists the links to those resource. I tried to made the contribution.md as compact as possible. And removed very basic things like creating a github account and stuff like that

2022-04-09 20:02 UTC, GemmaTuron approved these changes

2022-04-09 20:03 UTC, GemmaTuron commented
Hi @sayantani11 

Ok, I understand your reasoning thanks for the clarification.

2022-04-09 20:03 UTC, merged